### ISSUE TITLE
Cloudlfare again

### ISSUE THREAD

**Issue by 0xD4** [everywall/ladder#30]
Cloudflare is blocking again. I tried to change the user agent, then I get the paywal. With the default settings I get blocked.

ladder: 0.0.17
Test-URL: [tagesspiegel.de](https://www.tagesspiegel.de/wirtschaft/finanzen/verhaltensokonom-im-interview-es-gibt-an-der-borse-nur-funf-echte-risiken-10741153.html)
Screenshot: 

<img width="1197" alt="grafik" src="https://github.com/everywall/ladder/assets/12544860/97275226-64cb-44ff-a37b-844e472ca23e">

Could someone explain how the problem can be solved with the ruleset? Then I can try to find a solution myself.

**Comment by mms-gianni** [comment]
It seems they block the user-agent. 

To bypass this block you might use this rule. 

```yaml
- domain: tagesspiegel.de
  headers: 
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
    content-security-policy: "script-src 'self';"
```

But it seems they have no backdoor for search engines.
