### ISSUE TITLE
Cloudflare blocked

### ISSUE THREAD

**Issue by deoxykev** [everywall/ladder#5]
When I try something like:

https://ladder.mydomain.com/https://medium.com/mapresearch/does-the-fourth-industrial-revolution-have-a-new-path-818723d06030

I get:
```
Sorry, you have been blocked
You are unable to access medium.com

Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
```

From Cloudflare.

---

I'm using the following docker-compose config:

```yml
version: '3'
services:
  ladder:
    image: ghcr.io/kubero-dev/ladder:latest
    container_name: ladder
    build: .
    #restart: always
    #command: sh -c ./ladder
    environment:
      - PORT=8080
      #- PREFORK=true
      #- X_FORWARDED_FOR=66.249.66.1
      #- USER_AGENT=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
      #- USERPASS=foo:bar
      #- LOG_URLS=true
      #- GODEBUG=netdns=go
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128Mroot@ladder01:/opt# docker-compose up -d
```

Do you know of a workaround for Cloudflare?
